DROP SCHEMA TESTES;
CREATE SCHEMA IF NOT EXISTS TESTES;
SET SCHEMA TESTES;

DROP TABLE IF EXISTS PRODUTOS;
CREATE TABLE PRODUTOS (ID INT PRIMARY KEY, SKU VARCHAR(255), DESCRICAO VARCHAR(255), PRECO DOUBLE);

DROP TABLE IF EXISTS PEDIDOS;
CREATE TABLE PEDIDOS (ID INT PRIMARY KEY, PAGAMENTO_ID INT, UID_CORREIOS VARCHAR(255));

DROP TABLE IF EXISTS ITENS_PEDIDOS;
CREATE TABLE ITENS_PEDIDOS (ID INT PRIMARY KEY, PEDIDO_ID INT, PRODUTO_ID INT, QUANTIDADE INT);

DROP TABLE IF EXISTS PAGAMENTOS;
CREATE TABLE PAGAMENTOS (ID INT PRIMARY KEY, AUTORIZADO BOOLEAN, PEDIDO_ID INT);

ALTER TABLE PEDIDOS
    ADD FOREIGN KEY (PAGAMENTO_ID) 
    REFERENCES PAGAMENTOS(ID);
    
ALTER TABLE ITENS_PEDIDOS
    ADD FOREIGN KEY (PEDIDO_ID) 
    REFERENCES PEDIDOS(ID);
    
ALTER TABLE ITENS_PEDIDOS
    ADD FOREIGN KEY (PRODUTO_ID) 
    REFERENCES PRODUTOS(ID);
    
ALTER TABLE PAGAMENTOS
    ADD FOREIGN KEY (PEDIDO_ID) 
    REFERENCES PEDIDOS(ID);
    
    