CREATE TABLE PRODUTOS (
	ID_PRODUTO INTEGER CONSTRAINT PK_PRODUTO PRIMARY KEY,
	SKU VARCHAR(15) NOT NULL,
	PRECO DECIMAL(10,2) NOT NULL,
	DESCRICAO VARCHAR(255)
);

CREATE TABLE PEDIDOS (
	ID_PEDIDO INTEGER CONSTRAINT PK_PEDIDO PRIMARY KEY,
	UID_CORREIOS VARCHAR(25),
	ID_PAGAMENTO INTEGER
);

CREATE TABLE ITENS_PEDIDO (	
	ID_PRODUTO INTEGER NOT NULL,
	QUANTIDADE INTEGER NOT NULL,
	ID_PEDIDO INTEGER NOT NULL
);

CREATE TABLE PAGAMENTOS (
	ID_PAGAMENTO INTEGER CONSTRAINT PK_PAGAMENTO PRIMARY KEY,
	AUTORIZADO BOOLEAN,
	ID_PEDIDO INTEGER NOT NULL
);

ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES PAGAMENTOS (ID_PAGAMENTO);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO);

ALTER TABLE ITENS_PEDIDO ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO);

ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO);